name: Unit Test Coverage

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: "test"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run unit tests and check coverage
        run: ./gradlew -x spotlessCheck check
